### ISSUE TITLE
Cityscape crashes in 80-Column mode

### ISSUE THREAD

**Issue by bruno185** [thelbane/Apple-II-Programs#2]
Congratulation for your 1 ou 2 lines programs
I have found this bug, but not analysed it yet. 

Bruno

**Comment by thelbane** [comment]
Sorry for the delayed reply. All the programs here presume the machine is in the following state:

* Text mode
* 40-columns
* `Normal` characters
* Applesoft prompt
* DOS may be present, but is not required in most cases
